---
functional:
  - Успешная авторизация пользователя
  - Успешное создание новой игры
  - Успешное подключение второго игрока
  - Успешное ведение игры двумя игроками в режиме он-лайн
  - Корректное функционирование кнопки для проверки решения игрока
  - Корректное завершение игры
  - Корректное функционирование личного кабинета
  - Корректное функционирование чата
  - Корректное функционирование поиска и фильтров
  - Корректное функционирование кнопки возврата на главную страницу
  - Возможность выбора языка в задании
  - Возможность выбора языка программирования
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен обрабатывать большое количество трафика
implicit:
  - Интерфейс сайта должен быть в умеренной цветовой гамме
  - Шрифт сайта должен быть понятным и корректным
